Bedrock Support
DataSQRL/apiRAG pull request #3
Opened 2024-05-07 16:04 UTC by bilbo7833

## Support for Amazon Bedrock Models

Details to come later

2024-05-09 13:32 UTC, bilbo7833 commented on java/src/main/java/com/datasqrl/ai/models/bedrock/BedrockChatSession.java
> +  }
@mbroecheler This is the part which I changed to match the function call I described in the system prompt. But I am not sure what the LLM was trained on. Does the function call string description for OpenAIChatSession represent the OpenAPI standard and could Llama3 have been trained on this format?

2024-05-13 19:54 UTC, bilbo7833 commented
@mbroecheler Ready for review :)

2024-05-14 17:40 UTC, mbroecheler requested changes
This looks great. Let's refactor out the function injection from the user provided system message and store the function results differently. Hopefully it makes a difference.

2024-05-15 18:18 UTC, mbroecheler approved these changes

2024-05-15 18:18 UTC, merged